config/routes.rb
Rails.application.routes.draw do
  resources :templates, only: [:new, :create, :index, :show]

  resources :tags, only: [:create] do
    member do
      put :mass_update
    end
  end

  root 'templates#index'

  get '/help', to: 'static_pages#help'

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer          not null, primary key
#  description :string(255)
#  content     :string(255)
#  template_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Tag < ActiveRecord::Base
  validates :description, presence: true
  validates :template_id, presence: true

  belongs_to :template
end

app/models/template.rb
# == Schema Information
#
# Table name: templates
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  content    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Template < ActiveRecord::Base
  validates :content, presence: true
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  has_many :tags

  accepts_nested_attributes_for :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @template = Template.find(params[:template_id])
    @tag = @template.tags.build(tag_params)
    if @tag.save
      flash[:success] = "Tag Saved"
      redirect_to template_path(@template)
    else
      render '/templates/add_tag'
    end
  end

  def mass_update
    @template = Template.find(params[:id])
    @tags = @template.tags
    @tags.each_with_index do |tag, i|
      tag.update_attributes(content: params[:content][i])
    end
    redirect_to template_path(@template)
  end

  private

    def tag_params
      params.require(:tag).permit(:description, :template_id, :content)
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  def new
    @template = Template.new
  end

  def create
    @template = Template.new(template_params)
    if @template.save
      flash[:success] = "Template Saved"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @templates = Template.all
  end

  def show
    @template = Template.find(params[:id])
    @tags = @template.tags
    @tag = @template.tags.build
  end
  
  private
    def template_params
      params.require(:template).permit(:name, :content, tag_attributes: [:description, :template_id, :content])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Multiple Find and Replace"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Template Index", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Add Template", new_template_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

Help me!

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis tincidunt ligula, id gravida ligula vehicula vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus felis lectus, laoreet eu erat eget, tristique condimentum massa. Ut sit amet mi vel felis pretium placerat eu non lectus. Etiam cursus turpis nec metus facilisis tempus. Nulla facilisi. Sed libero neque, porta convallis augue quis, egestas rhoncus augue. In ut nisl varius, congue metus at, lacinia mi. Aliquam id urna purus. Quisque feugiat dignissim libero, a posuere justo pulvinar vitae. Nullam eget elit aliquam, sollicitudin sapien ut, bibendum libero. Nullam ut consequat mi. Sed semper massa leo, sit amet sagittis odio venenatis ut. Duis mauris tellus, ullamcorper id elit nec, feugiat ultricies justo. Vestibulum lobortis sollicitudin rhoncus. Vestibulum turpis nunc, pretium quis vehicula at, scelerisque id metus.

Donec interdum fermentum volutpat. Donec mattis orci vitae nibh aliquet, at hendrerit diam vehicula. Proin et sem purus. In sit amet dui sit amet dolor auctor rutrum sed ut nulla. Morbi erat odio, sodales vitae placerat sit amet, fringilla id ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam eros lacus, vulputate vehicula interdum a, faucibus vitae velit.

Aliquam sed dolor interdum, fringilla augue nec, aliquet felis. Suspendisse vitae sollicitudin augue. Nulla eleifend malesuada arcu, at interdum dolor fringilla eu. Cras nec nulla eu ligula fermentum mollis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum a magna urna. Mauris consectetur nisl ut lectus consequat, sed fringilla dui porta. Curabitur nisi metus, viverra ut dolor eu, eleifend aliquam risus.

Cras feugiat sapien a sollicitudin tempus. Quisque varius ultricies enim eget ornare. Donec mi nisl, iaculis nec est in, pellentesque condimentum tellus. Duis neque metus, convallis a purus non, adipiscing ultrices sem. Fusce vitae egestas sapien, quis dignissim odio. Aliquam accumsan cursus arcu, eu luctus tellus faucibus sed. Donec sollicitudin ipsum et dolor porta, id auctor arcu pretium. Integer est ipsum, laoreet eu tempus sed, fermentum vitae metus. Donec vehicula risus ante, quis aliquam nunc ullamcorper vel. Nunc lorem ante, suscipit eu felis volutpat, rutrum adipiscing nulla. Ut blandit ipsum non odio vestibulum, quis feugiat ante molestie. Suspendisse ut posuere lorem. Curabitur mollis libero nec magna mollis pharetra. Aenean ultrices feugiat aliquet.

Phasellus pharetra consectetur dui, sed interdum quam venenatis a. Vivamus et luctus magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec auctor lorem in tempus porta. Vivamus rhoncus suscipit ligula, nec tincidunt dui lacinia a. Suspendisse interdum mollis ligula a laoreet. Duis malesuada ultricies sodales. Sed volutpat consequat enim et hendrerit. Maecenas porta risus vitae felis porta, ut dictum magna tincidunt. Cras vel lorem vehicula, mattis lacus eget, dictum metus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis tincidunt ligula, id gravida ligula vehicula vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus felis lectus, laoreet eu erat eget, tristique condimentum massa. Ut sit amet mi vel felis pretium placerat eu non lectus. Etiam cursus turpis nec metus facilisis tempus. Nulla facilisi. Sed libero neque, porta convallis augue quis, egestas rhoncus augue. In ut nisl varius, congue metus at, lacinia mi. Aliquam id urna purus. Quisque feugiat dignissim libero, a posuere justo pulvinar vitae. Nullam eget elit aliquam, sollicitudin sapien ut, bibendum libero. Nullam ut consequat mi. Sed semper massa leo, sit amet sagittis odio venenatis ut. Duis mauris tellus, ullamcorper id elit nec, feugiat ultricies justo. Vestibulum lobortis sollicitudin rhoncus. Vestibulum turpis nunc, pretium quis vehicula at, scelerisque id metus.

Donec interdum fermentum volutpat. Donec mattis orci vitae nibh aliquet, at hendrerit diam vehicula. Proin et sem purus. In sit amet dui sit amet dolor auctor rutrum sed ut nulla. Morbi erat odio, sodales vitae placerat sit amet, fringilla id ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam eros lacus, vulputate vehicula interdum a, faucibus vitae velit.

Aliquam sed dolor interdum, fringilla augue nec, aliquet felis. Suspendisse vitae sollicitudin augue. Nulla eleifend malesuada arcu, at interdum dolor fringilla eu. Cras nec nulla eu ligula fermentum mollis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum a magna urna. Mauris consectetur nisl ut lectus consequat, sed fringilla dui porta. Curabitur nisi metus, viverra ut dolor eu, eleifend aliquam risus.

Cras feugiat sapien a sollicitudin tempus. Quisque varius ultricies enim eget ornare. Donec mi nisl, iaculis nec est in, pellentesque condimentum tellus. Duis neque metus, convallis a purus non, adipiscing ultrices sem. Fusce vitae egestas sapien, quis dignissim odio. Aliquam accumsan cursus arcu, eu luctus tellus faucibus sed. Donec sollicitudin ipsum et dolor porta, id auctor arcu pretium. Integer est ipsum, laoreet eu tempus sed, fermentum vitae metus. Donec vehicula risus ante, quis aliquam nunc ullamcorper vel. Nunc lorem ante, suscipit eu felis volutpat, rutrum adipiscing nulla. Ut blandit ipsum non odio vestibulum, quis feugiat ante molestie. Suspendisse ut posuere lorem. Curabitur mollis libero nec magna mollis pharetra. Aenean ultrices feugiat aliquet.

Phasellus pharetra consectetur dui, sed interdum quam venenatis a. Vivamus et luctus magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec auctor lorem in tempus porta. Vivamus rhoncus suscipit ligula, nec tincidunt dui lacinia a. Suspendisse interdum mollis ligula a laoreet. Duis malesuada ultricies sodales. Sed volutpat consequat enim et hendrerit. Maecenas porta risus vitae felis porta, ut dictum magna tincidunt. Cras vel lorem vehicula, mattis lacus eget, dictum metus.

app/views/static_pages/home.html.erb
<div class="container" id="container">
  <textarea id="original"></textarea>
  <textarea id="final"></textarea>

  <button id="button">Replace!</button><br/>

  <% x = (1..10).to_a %>
  <% x.each_with_index do |item, index| %>
    <label><%= "{a" + (index + 1).to_s + "}" %></label><input type='text' id="<%= 'a' + (index + 1).to_s %>" class='replace_element'>
  <% end %>

  <button id="addItem">Add Item</button><br/>
</div>

app/views/templates/index.html.erb
<% provide(:title, 'All Templates') %>

<div class = "row">
  <% @templates.each do |t| %>
    <div class="col-md-4">
      <b><%= link_to t.name, template_path(t) %></b>
    </div>
    <div class="col-md-8">
      <textarea rows="10"><%= t.content %></textarea>
    </div>
  <% end %>
</div>

app/views/templates/new.html.erb
<% provide(:title, 'Add Template') %>

<div class = "row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Add Template</h1>
    <hr>
    <%= form_for @template do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :content %>
      <%= f.text_area :content, rows: 10 %>

      <%= f.submit "Add Template", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/templates/show.html.erb
<div class="container" id="container">
  <h2><%= @template.name %></h2>
  <div class="row">
    <div class="col-sm-6">
      <textarea rows="10" id="original"><%= @template.content %></textarea>
    </div>
    <div class="col-sm-6">
      <textarea rows="10" id="final"></textarea>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= form_tag mass_update_tag_path, method: :put, id: "update_tag_form" do %>
        <% count = @tags.count %>
        <% @tags.each_with_index do |tag, index| %>
          <% break if index == count %>
          <label><%= "{a" + (index + 1).to_s + "}" %> <%= tag.description %></label>
          <%= hidden_field_tag "tag_id[]", tag.id %>
          <%= text_field_tag "content[]", tag.content, class: "replace_element" %>
        <% end %>
      <% end %>

      <div class="row">
        <div class="col-xs-6"><%= button_tag "Update Tags", id: "submit_updates", class: "btn btn-primary" %></div>
        <div class="col-xs-6 "><%= button_tag "Replace!", id: "button", class: "btn btn-primary" %></div>
      </div>

      <hr>
      <h3>Add Tag</h3>
      <%= form_for(@tag, url: tags_path(template_id: @template)) do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <label><%= "{a" + (@tags.count + 1).to_s + "}" %></label>
        <%= f.label :description %>
        <%= f.text_field :description %>

        <%= f.label :content %>
        <%= f.text_area :content, rows: 10 %>

        <%= f.submit "Add Tag", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
</div>